### ISSUE TITLE
Abstract Service Class NullPointerException

### ISSUE THREAD

**Issue by mjp91** [leangen/graphql-spqr#10]
I'm trying to implement an abstract class with some generics to cut down on code duplication.

Abstract class:

```java
public abstract class AbstractResolver<T extends AbstractEntity> {
  protected QueryDslRepository<T> repository;

  public AbstractResolver(QueryDslRepository<T> repository) {
    this.repository = repository;
  }

  public List<T> findAll(T entity, Integer limit, Integer offset) {
    ...
  }
}

```

Concrete class:

```java
@Component
public class BankResolver extends AbstractResolver<Bank> {
  @Autowired
  public BankResolver(BankRepository bankRepository) {
    super(bankRepository);
  }

  @GraphQLQuery(name = "bank")
  public Bank findById(Long id) {
    return super.repository.findOne(id);
  }

  @GraphQLQuery(name = "banks")
  public List<Bank> findAll(Bank bank, Integer limit, Integer offset) throws IntrospectionException, InvocationTargetException, IllegalAccessException {
    return super.findAll(bank, limit, offset);
  }

  @GraphQLMutation(name = "bankUpdate")
  public Bank save(Bank bank) {
    return super.repository.save(bank);
  }
}
```

However upon making this change I get the following NullPointerException:

```
Caused by: java.lang.NullPointerException
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.supports(NonNullMapper.java:52)
	at io.leangen.graphql.generator.mapping.TypeMapperRepository.lambda$getTypeMapper$46(TypeMapperRepository.java:19)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at io.leangen.graphql.generator.mapping.TypeMapperRepository.getTypeMapper(TypeMapperRepository.java:19)
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:150)
	at io.leangen.graphql.generator.mapping.common.ListMapper.toGraphQLType(ListMapper.java:23)
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:150)
	at io.leangen.graphql.generator.OperationMapper.toGraphQLOperation(OperationMapper.java:122)
	at io.leangen.graphql.generator.OperationMapper.lambda$generateQueries$20(OperationMapper.java:82)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.leangen.graphql.generator.OperationMapper.generateQueries(OperationMapper.java:83)
	at io.leangen.graphql.generator.OperationMapper.<init>(OperationMapper.java:67)
	at io.leangen.graphql.GraphQLSchemaGenerator.generate(GraphQLSchemaGenerator.java:692)
	at p4.config.GraphQLConfig.graphQLSchema(GraphQLConfig.java:30)
	at p4.config.GraphQLConfig$$EnhancerBySpringCGLIB$$a5f5ad92.CGLIB$graphQLSchema$1(<generated>)
	at p4.config.GraphQLConfig$$EnhancerBySpringCGLIB$$a5f5ad92$$FastClassBySpringCGLIB$$ca17212f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at p4.config.GraphQLConfig$$EnhancerBySpringCGLIB$$a5f5ad92.graphQLSchema(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 86 more
```

**Comment by kaqqao** [comment]
This smells like another type reconciliation problem, e.g. two methods with the same query name, both returning lists, but different kinds.

Do you directly expose `BankResolver ` via `schemaGenerator.withOperationsFromSingleton(new BankResolver())` or is `BankResolver` a type discovered through some other service?

**Comment by kaqqao** [comment]
OK, I found the problem. I've seen this one before and thought I had solved it. Luckily, you can easily work around it yourself before I release a fix.

**In-depth description of what happens:**

Due to the generics and inheritance, a [bridge method](https://docs.oracle.com/javase/tutorial/java/generics/bridgeMethods.html) gets generated by Java and picked up by the `ResolverBuilder`, so there ends up being 2 resolvers for the same query. The bridge method has a raw return type, and the process attempts merging the return types of the two methods, it can only come with the raw type, breaking further mapping.

**Work-around:**

Simply filter out bridge and synthetic methods yourself, e.g.

```java
ResolverBuilder filteringBuilder = new AnnotatedResolverBuilder().withFilters(
                m -> (!(m instanceof Method) || !((Method) m).isBridge()) && !m.isSynthetic());
        
GraphQLSchema schemaFromAnnotated = new GraphQLSchemaGenerator()
            .withBasePackage("your.base.package")
            .withResolverBuilders(filteringBuilder) //register the custom builder globally
            .withOperationsFromSingleton(bankResolver), BankResolver.class, filteringBuilder) //or only for this bean
            .generate();
```
