### ISSUE TITLE
Cannot construct instance of `io.leangen.graphql.generator.mapping.common.ObjectScalarAdapter$ScalarMap`

### ISSUE THREAD

**Issue by psgliniecki** [leangen/graphql-spqr#106]
First of all, thanks for this great lib! :)

I have the following setting: 

- graphql-spqr 0.9.7

- a singleton service with query method that returns a TryoutObj pojo:

```
    @GraphQLQuery
	public TryoutObj someQuery() {
		return new TryoutObj("test");
	}
```

- the pojo is defined as follows:

```
        public class TryoutObj {		
		private Object val;
		private String name;
		public TryoutObj() {}
		public TryoutObj(Object val) {
			this.val = val;
		}
		public Object getVal() {
			return val;
		}
		public void setVal(Object val) {
			this.val = val;
		}
		public String getName() {
			return name;
		}
		public void setName(String name) {
			this.name = name;
		}
	}
```

- I get a Jackson exception on executing query (using GraphiQL client, but it shouldn't be of importance) - full stack below:

> java.lang.IllegalArgumentException: Cannot construct instance of `io.leangen.graphql.generator.mapping.common.ObjectScalarAdapter$ScalarMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('test')
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3738) ~[jackson-databind-2.9.3.jar!/:2.9.3]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3676) ~[jackson-databind-2.9.3.jar!/:2.9.3]
	at io.leangen.graphql.metadata.strategy.value.jackson.JacksonValueMapper.fromInput(JacksonValueMapper.java:49) ~[spqr-0.9.7.jar!/:na]
	at io.leangen.graphql.generator.mapping.common.ObjectScalarAdapter.convertOutput(ObjectScalarAdapter.java:43) ~[spqr-0.9.7.jar!/:na]
	at io.leangen.graphql.generator.mapping.common.ObjectScalarAdapter.convertOutput(ObjectScalarAdapter.java:21) ~[spqr-0.9.7.jar!/:na]
	at io.leangen.graphql.execution.ResolutionEnvironment.convertOutput(ResolutionEnvironment.java:49) ~[spqr-0.9.7.jar!/:na]
	at io.leangen.graphql.execution.OperationExecutor.execute(OperationExecutor.java:52) ~[spqr-0.9.7.jar!/:na]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:227) [graphql-java-8.0.jar!/:na]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:170) [graphql-java-8.0.jar!/:na]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59) ~[graphql-java-8.0.jar!/:na]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:551) [graphql-java-8.0.jar!/:na]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:375) [graphql-java-8.0.jar!/:na]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:332) [graphql-java-8.0.jar!/:na]
	at graphql.execution.ExecutionStrategy.lambda$resolveField$0(ExecutionStrategy.java:172) [graphql-java-8.0.jar!/:na]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[na:1.8.0_161]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[na:1.8.0_161]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:171) [graphql-java-8.0.jar!/:na]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59) ~[graphql-java-8.0.jar!/:na]
	at graphql.execution.Execution.executeOperation(Execution.java:158) ~[graphql-java-8.0.jar!/:na]
	at graphql.execution.Execution.execute(Execution.java:100) ~[graphql-java-8.0.jar!/:na]
	at graphql.GraphQL.execute(GraphQL.java:558) ~[graphql-java-8.0.jar!/:na]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:500) ~[graphql-java-8.0.jar!/:na]
	at graphql.GraphQL.executeAsync(GraphQL.java:470) ~[graphql-java-8.0.jar!/:na]
	at graphql.GraphQL.execute(GraphQL.java:401) ~[graphql-java-8.0.jar!/:na]
	at graphql.GraphQL.execute(GraphQL.java:371) ~[graphql-java-8.0.jar!/:na]
    ...
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `io.leangen.graphql.generator.mapping.common.ObjectScalarAdapter$ScalarMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('test')
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63) ~[jackson-databind-2.9.3.jar!/:2.9.3]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342) ~[jackson-databind-2.9.3.jar!/:2.9.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1031) ~[jackson-databind-2.9.3.jar!/:2.9.3]
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371) ~[jackson-databind-2.9.3.jar!/:2.9.3]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323) ~[jackson-databind-2.9.3.jar!/:2.9.3]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:357) ~[jackson-databind-2.9.3.jar!/:2.9.3]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29) ~[jackson-databind-2.9.3.jar!/:2.9.3]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3733) ~[jackson-databind-2.9.3.jar!/:2.9.3]
	... 82 common frames omitted

- I had a look at ObjectScalarAdapter and noticed it has:

``` 
    @Override
    public Map<String, ?> convertOutput(Object original, AnnotatedType type, ResolutionEnvironment resolutionEnvironment) {
        return resolutionEnvironment.valueMapper.fromInput(original, type.getType(), MAP);
    }
```
that will probably throw on simple String input as the MAP is a subclass of LinkedHashMap. 

An input based on this object with object scalar definition works perfectly as in .parseFieldValue(Value value) found in Scalars.java:203 there are some conditions that catch primitive/simple values, only the output is troublesome.  

Is this a desired behavior or have I missed some config that needs to be there for this to work properly?

**Comment by psgliniecki** [comment]
As a quick walkaround for a bit narrow use case I used:

`.withOutputConverters((config, defaults) -> defaults.drop(ObjectScalarAdapter.class))`

it works with

`return new TryoutObj("test");`

as well as with:

`return new TryoutObj(new HashMap<String, Object>(){{put("foo", 845);}});`

although I guess there might be some other features that will be disabled by doing so?

**Comment by kaqqao** [comment]
Yup, you figured out exactly what I wanted to suggest :)
Version 0.9.8 will probably drop the `ObjectScalarAdapter ` from output converters by default, as it caused more trouble than it's worth.

There only 2 possible downsides (both minor IMHO):
* If you're directly consuming the query result (without first serializing it to JSON), and the client expects to receive either maps or scalars (what graphql-java would normally return), it could get confused.
* If your JSON library used to serialize the result doesn't know how to deal with the returned object, or is misconfigured, you could get unexpected results

Both are fringe cases that you probably don't care about.

**Comment by psgliniecki** [comment]
Thanks! :)
