### ISSUE TITLE
Defining two GraphQLQuery with the same name results in IndexOutOfBoundsException

### ISSUE THREAD

**Issue by IvoLimmen** [leangen/graphql-spqr#12]
I have a service with two methods and (not knowing GraphQL really well) defined two methods with:
    @GraphQLQuery(name = "person")
Resulting in:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at io.leangen.graphql.util.ClassUtils.getCommonSuperType(ClassUtils.java:396)
	at io.leangen.graphql.metadata.strategy.query.DefaultOperationBuilder.resolveJavaType(DefaultOperationBuilder.java:58)
	at io.leangen.graphql.metadata.strategy.query.DefaultOperationBuilder.buildQuery(DefaultOperationBuilder.java:33)
	at io.leangen.graphql.generator.OperationRepository.lambda$buildQueries$39(OperationRepository.java:38)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.leangen.graphql.generator.OperationRepository.buildQueries(OperationRepository.java:39)
	at io.leangen.graphql.generator.OperationRepository.<init>(OperationRepository.java:31)
	at io.leangen.graphql.GraphQLSchemaGenerator.generate(GraphQLSchemaGenerator.java:685)
```
Would be nice if the generator throws an exception while initializing that this is not allowed.

**Comment by kaqqao** [comment]
It is in fact allowed to have multiple methods with the same method. The problem here is that in your case they are probably returning different types, and the current logic for handling of this is flaky when dealing with generic types. I'm already working on this.

**Comment by IvoLimmen** [comment]
@kaqqao you where right: I had two different return types. Using one return type fixes the problem! Thank you for responding so quick.

**Comment by kaqqao** [comment]
In the next release, I'll try to make this behavior opt-in, as it is causing confusion for a lot of people.

When there's multiple methods acting as one, all their arguments get collected, and depending on what inputs the client sends, the matching method will be called. But, this means default values can no longer be used in a sensible way, and all the arguments satisfying one of the methods must be provided.

One good use-case for having multiple methods thought is unions. If you for example have 2 methods like this:
```java
public @GraphQLUnion String methodOne() {...}

public @GraphQLUnion Long methodTwo() {...}
```
you'll end up producing a query returning a Union type (possible concrete types being String and Int).

You can take it much further too, e.g.
```java
public List<@GraphQLUnion String> methodOne() {...}

public List<@GraphQLUnion Long> methodTwo() {...}
```
will produce a query returning a list of Unions, etc.

**Comment by IvoLimmen** [comment]
Sounds like a really neat and useful addition.
