### ISSUE TITLE
NPE in AnnotatedOperationNameGenerator

### ISSUE THREAD

**Issue by nickhristov** [leangen/graphql-spqr#142]
Stack trace:

```
Caused by: java.lang.NullPointerException: null
	at io.leangen.graphql.metadata.strategy.query.AnnotatedOperationNameGenerator.queryName(AnnotatedOperationNameGenerator.java:33) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.metadata.strategy.query.AnnotatedOperationNameGenerator.generateQueryName(AnnotatedOperationNameGenerator.java:19) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.metadata.strategy.query.BeanOperationNameGenerator.generateQueryName(BeanOperationNameGenerator.java:18) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.metadata.strategy.query.PublicResolverBuilder.lambda$buildQueryResolvers$1(PublicResolverBuilder.java:67) ~[spqr-0.9.6.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_102]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_102]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_102]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_102]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_102]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_102]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_102]
	at io.leangen.graphql.metadata.strategy.query.PublicResolverBuilder.buildQueryResolvers(PublicResolverBuilder.java:75) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.metadata.strategy.query.PublicResolverBuilder.buildQueryResolvers(PublicResolverBuilder.java:46) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationRepository.lambda$buildQueryResolvers$16(OperationRepository.java:137) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationRepository.lambda$null$19(OperationRepository.java:154) ~[spqr-0.9.6.jar:na]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[na:1.8.0_102]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_102]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_102]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_102]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_102]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_102]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[na:1.8.0_102]
	at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[na:1.8.0_102]
	at java.util.Collections$2.forEachRemaining(Collections.java:4725) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_102]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_102]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_102]
	at io.leangen.graphql.generator.OperationRepository.buildResolvers(OperationRepository.java:156) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationRepository.buildQueryResolvers(OperationRepository.java:136) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationRepository.buildNestedQueries(OperationRepository.java:132) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationRepository.getNestedQueries(OperationRepository.java:108) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationRepository.getChildQueries(OperationRepository.java:114) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getFields(ObjectTypeMapper.java:82) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:39) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:31) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.mapping.common.CachingMapper.graphQLType(CachingMapper.java:28) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.mapping.common.AbstractionCollectingMapper.toGraphQLType(AbstractionCollectingMapper.java:28) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:171) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.mapping.common.ListMapper.toGraphQLType(ListMapper.java:23) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:171) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.mapping.common.AbstractTypeSubstitutingMapper.toGraphQLType(AbstractTypeSubstitutingMapper.java:23) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:171) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:136) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.lambda$getFields$3(ObjectTypeMapper.java:83) ~[spqr-0.9.6.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_102]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_102]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_102]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_102]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getFields(ObjectTypeMapper.java:84) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:39) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:31) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.mapping.common.CachingMapper.graphQLType(CachingMapper.java:28) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.mapping.common.AbstractionCollectingMapper.toGraphQLType(AbstractionCollectingMapper.java:28) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:171) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.mapping.common.ListMapper.toGraphQLType(ListMapper.java:23) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:171) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:136) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationMapper.lambda$generateQueries$0(OperationMapper.java:90) ~[spqr-0.9.6.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_102]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_102]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_102]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_102]
	at io.leangen.graphql.generator.OperationMapper.generateQueries(OperationMapper.java:91) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.generator.OperationMapper.<init>(OperationMapper.java:74) ~[spqr-0.9.6.jar:na]
	at io.leangen.graphql.GraphQLSchemaGenerator.generate(GraphQLSchemaGenerator.java:794) ~[spqr-0.9.6.jar:na]
```

Will submit a PR in a bit.

**Comment by kaqqao** [comment]
Closed via https://github.com/leangen/graphql-spqr/commit/6fe60e21bef4e9fab956c459b98aece82628ac65

The interface for `OperationNameGenerator` was changed to now accept `OperationNameGeneratorParams`. This is a breaking change, but will allow easier API evolution (with fewer breaking changes) in the future.

Additionally, all built-in `OperationNameGenerator`s have been simplified for easier usage with different `ResolverBuilder`s.
