### ISSUE TITLE
Parsing Scalar Variables in a Query is Invoking the Serialise Method instead of Parse Literal

### ISSUE THREAD

**Issue by alissongodoi** [leangen/graphql-spqr#19]
I have declared the following method signature:
```
	@GraphQLQuery(name="findNextGymDayProgram")
	List<GymDayProgram> findNextGymDayProgram(@GraphQLArgument(name = "id") long id,
			@GraphQLArgument(name = "startDate") LocalDate startDate,
			@GraphQLArgument(name = "days") int days);
```

When using the following variables, for instance:
```
query deviceService_findNextGymDayProgram($id:Long!,$startDate:LocalDate!,$days:Int!) {
  deviceService_findNextGymDayProgram(id:$id,startDate:$startDate,days:$days) {
    id
  }
}

{"id":"1", "startDate": "2017-01-01","days":30}
```

The method Scalar Temporal Serialize is being invoked throwing the following exception:
```Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Date
	at io.leangen.graphql.util.Scalars$5.serialize(Scalars.java:190)
	at io.leangen.graphql.util.Scalars$5.parseValue(Scalars.java:195)
	at graphql.execution.ValuesResolver.coerceValueForScalar(ValuesResolver.java:109)
	at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:78)
	at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:68)
	at graphql.execution.ValuesResolver.getVariableValue(ValuesResolver.java:59)
	at graphql.execution.ValuesResolver.getVariableValues(ValuesResolver.java:16)
	at graphql.execution.ExecutionContextBuilder.build(ExecutionContextBuilder.java:63)
	at graphql.execution.Execution.execute(Execution.java:48)
	at graphql.GraphQL.execute(GraphQL.java:222)
```

This is a minor issue since it is possible to change methods signature to use String directly instead of Scalars.

**Comment by depauwjimmy** [comment]
I have had problems when declaring primitive as parameter types.
Have you tried using object variant for the primitive like Long and Integer?
