### ISSUE TITLE
@GraphQLContext in subQueries

### ISSUE THREAD

**Issue by pepijno** [leangen/graphql-spqr#230]
When using `@GraphQLContext` in a query defined in the root the context works as expected. If I use the `@GraphQLContext` in a subquery however, the method with the context annotation is registered as a query instead of adding a field.

For example if  have:
```java
class rootQueries {
    private UserService userService;
    ...

    @GraphQLQuery
    public UserService getUserService() {
        return this.userService;
    }
}

class UserService {

    ... //regular queries, as above

    // Attach a new field called twitterProfile to the User GraphQL type
    @GraphQLQuery
    public TwitterProfile twitterProfile(@GraphQLContext User user) {
      ...
    }
}
```
the twitterProfile is added as query instead of adding a field `twitterProfile` to the `User`. Also, executing the query
```graphql
getUserService {
    twitterProfile {
        ...
    }
}
```
throws an `IllegalArgumentException` with the following stacktrace:
```
java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202-release]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202-release]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202-release]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202-release]
	at io.leangen.graphql.metadata.execution.MethodInvoker.execute(MethodInvoker.java:26) ~[spqr-0.9.9.jar:na]
	at io.leangen.graphql.metadata.Resolver.resolve(Resolver.java:100) ~[spqr-0.9.9.jar:na]
	at io.leangen.graphql.execution.OperationExecutor.lambda$execute$1(OperationExecutor.java:93) ~[spqr-0.9.9.jar:na]
	at io.leangen.graphql.execution.OperationExecutor.execute(OperationExecutor.java:98) ~[spqr-0.9.9.jar:na]
	at io.leangen.graphql.execution.OperationExecutor.execute(OperationExecutor.java:94) ~[spqr-0.9.9.jar:na]
	at io.leangen.graphql.execution.OperationExecutor.execute(OperationExecutor.java:59) ~[spqr-0.9.9.jar:na]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:261) [graphql-java-11.0.jar:na]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:202) [graphql-java-11.0.jar:na]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:70) ~[graphql-java-11.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:636) [graphql-java-11.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:416) [graphql-java-11.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:366) [graphql-java-11.0.jar:na]
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:204) [graphql-java-11.0.jar:na]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[na:1.8.0_202-release]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[na:1.8.0_202-release]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[na:1.8.0_202-release]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203) [graphql-java-11.0.jar:na]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:70) ~[graphql-java-11.0.jar:na]
	at graphql.execution.Execution.executeOperation(Execution.java:159) ~[graphql-java-11.0.jar:na]
	at graphql.execution.Execution.execute(Execution.java:101) ~[graphql-java-11.0.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:573) ~[graphql-java-11.0.jar:na]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:515) ~[graphql-java-11.0.jar:na]
	at graphql.GraphQL.executeAsync(GraphQL.java:489) ~[graphql-java-11.0.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:420) ~[graphql-java-11.0.jar:na]
        ...
```

Is there any way that using `@GraphQLContext` in subqueries is possible by using or adding some configuration to `spqr`?

This issue was present in version `0.9.9`.

**Comment by kaqqao** [comment]
`@GraphQLContext` effectively injects the result of the parent query (`DataFetcher#getSource`). When executing a resolver method for a nested query, the _result of the parent query_ is the current instance (the same as `this`). So the `@GraphQLContext` annotation logically only makes sense in a top-level query.

Moreover, you can think of `@GraphQLContext` as a way to establish relations between otherwise disconnected types. All the types exist at the same level, so the connections between them also exist on a single level, nesting simply makes no sense there.

I believe the reason you got confused is the extra level you introduced into your structure that doesn't actually exist. All services registered with the generator _are top/root level_, so the `RootQueries` class shouldn't actually exist, in the sense that it doesn't semantically map to anything. `UserService` should be one of the root classes.

**Comment by pepijno** [comment]
Thanks, that actually makes sense. I suspected something like that but I wrongly assumed it must have been possible in some way. Guess I have to redesign my schema and look into the dos and don'ts of GraphQL schemas.
