### ISSUE TITLE
Batched nested fields queries

### ISSUE THREAD

**Issue by galiatsatosc** [leangen/graphql-spqr#26]
Overall Im pretty happy with this API. I was able to create successfully a graphQl  server exposing liferay's ORM model entities. The problem is that when i tried to implement a batched query for a nested model field i ended with java.lang.IllegalArgumentException: argument type mismatch and graphql.GraphQLException: Operation resolution exception. 

Searching the examples i found the education batched query method inside RecService in the tests of the repo and i used it to see if Im doing something wrong. But i get the same error even with this examples.
method:
@GraphQLQuery
    @Batched
    public List<Education> education(@GraphQLContext List<SimpleUser> users) {
    	System.out.println(users.size());
        return users.stream()
                .map(u -> u.getEducation(2000 + u.getFullName().charAt(0)))
                .collect(Collectors.toList());
    }
Query:
{  
  user(name:"Test") {
    fullName
    education {
      startYear
      tier
      schoolName
      endYear
      extra
    }
  }
}
Errors:
 Operation resolution exception
java.lang.IllegalArgumentException: argument type mismatch
Exception while fetching data (/user/education) : Operation resolution exception
graphql.GraphQLException: Operation resolution exception
at io.leangen.graphql.execution.OperationExecutor.execute(OperationExecutor.java:64)
	at io.leangen.graphql.generator.OperationMapper$1.get(OperationMapper.java:278)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:218)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:166)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:49)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:379)
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:297)
	at graphql.execution.ExecutionStrategy.lambda$resolveField$0(ExecutionStrategy.java:168)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:167)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:49)
	at graphql.execution.Execution.executeOperation(Execution.java:112)
	at graphql.execution.Execution.execute(Execution.java:65)
	at graphql.GraphQL.execute(GraphQL.java:466)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:414)
	at graphql.GraphQL.executeAsync(GraphQL.java:392)
	at graphql.GraphQL.execute(GraphQL.java:329)

**Comment by kaqqao** [comment]
I see some unexpected calls in the stack. Are you maybe trying to use graphql-spqr with graphql-java v4?

**Comment by galiatsatosc** [comment]
Yes you are right, Im using  graphql-java v4.2. I will try to use v3 and see if it works.

**Comment by kaqqao** [comment]
v4 is not supported yet, so I expect all sorts of colorful explosions with it.
If you just declare a dependency to graphql-spqr, it will drag in a compatible version (v3) and it should work fine with that.

**Comment by galiatsatosc** [comment]
Unfortunately in liferay 7 you have to treat every dependency separately, including nested dependencies,  cause of the bundle mechanisms but i used v3 and it worked perfectly. I have to say graphql-spqr is the simplest way to build graphql apis with java. Thanks for your help.
