### ISSUE TITLE
Unresolvable interface type - NullPointerException

### ISSUE THREAD

**Issue by frensjan** [leangen/graphql-spqr#299]
I'm experiencing a NullPointerException with SPQR while generating the GraphQL schema. See the stack trace below.

Normally I'd provide a unit test replicating the issue, but I'm not fully able to pin down the issue myself.

The crux of it is that in ```AbstractInterfaceMappingStrategy#getInterfaces(...)``` there is a loop (stream) over the interfaces of a class, where ```GenericTypeReflector.getExactSuperType``` is used that can return a null value, but the subsequent filter in the stream ```AbstractInterfaceMappingStrategy#supports(...)``` is unable to handle that.

Actually, depending on the value of ```AbstractInterfaceMappingStrategy#mapClasses``` it delegates to ```AbstractInterfaceMappingStrategy#supportsInterface``` but none of the implementations are able to handle that either. In my case, the NPE is raised in ```AnnotatedInterfaceStrategy#supportsInterface```.

---

A fix could be to filter any null values:
```java
Arrays.stream(clazz.getInterfaces())
      .map(inter -> GenericTypeReflector.getExactSuperType(type, inter))
      .filter(Objects::nonNull) // ADD: remove any interfaces for which a super type can't be extracted.
      .filter(this::supports)
      .forEach(interfaces::add);
```

That said, I must admit that I'm not 100% sure about this code exactly does. So I don't know if this an actual solution or that it fights symptoms of a larger issue that just happens to surface here for me now.

---

As a bit of background, the type for which this issue occurs is something along the lines of:

```java
public class NameElement extends SequencePropertyElement<NameElement.Role, String> {

    public enum Role {
        ...
    }

    protected Role role;
    protected String value;

    ...
```

With a parent class along the lines of:

```java
public abstract class SequencePropertyElement<R, V> {

    public abstract R getRole();

    public abstract V getValue();

    ...
}
```

The ```NameElement``` is used like:
```java
    private List<@GraphQLNonNull NameElement> value = new ArrayList<>();

    ...

    @GraphQLNonNull
    public List<@GraphQLNonNull NameElement> getValue() {
        return value;
    }

    ...
```

My estimate is that these classes should normally be just fine for SPRQ. However, I'm using [ebean.io](https://ebean.io) as an ORM. And the interface that ```GenericTypeReflector#getExactSuperType(...)``` isn't able to find a super type for is ```io.ebean.bean.EntityBean```. This interface gets 'mixed' in by ebean in an code enhancement process. That's also the reason why this is a little more difficult to capture in a simple unit test.

If I'm doing something wrong: let me know :)
Also, let me know if I can provide any further information if this is an issue to pin down further / resolve.

I'm working around it for now by configuring a custom ```InterfaceMappingStrategy``` extending ```AnnotatedInterfaceStrategy``` that adds the null check.

---

Stack trace for the issue:

```
...
Caused by: java.lang.NullPointerException
	at io.leangen.graphql.generator.mapping.strategy.AnnotatedInterfaceStrategy.supportsInterface(AnnotatedInterfaceStrategy.java:18) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.strategy.AbstractInterfaceMappingStrategy.supports(AbstractInterfaceMappingStrategy.java:25) ~[spqr-0.10.0.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_144]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_144]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_144]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_144]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_144]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_144]
	at io.leangen.graphql.generator.mapping.strategy.AbstractInterfaceMappingStrategy.getInterfaces(AbstractInterfaceMappingStrategy.java:44) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getInterfaces(ObjectTypeMapper.java:102) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:42) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLType(CachingMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:66) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:35) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:183) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ListMapper.toGraphQLType(ListMapper.java:23) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:66) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:35) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:183) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:146) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:176) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.lambda$getFields$5(ObjectTypeMapper.java:90) ~[spqr-0.10.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_144]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_144]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_144]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_144]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getFields(ObjectTypeMapper.java:91) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:39) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLType(CachingMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:66) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:35) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:183) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ListMapper.toGraphQLType(ListMapper.java:23) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:66) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:35) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:183) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:146) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:176) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.lambda$getFields$5(ObjectTypeMapper.java:90) ~[spqr-0.10.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_144]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_144]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_144]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_144]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getFields(ObjectTypeMapper.java:91) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:39) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLType(CachingMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:66) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:35) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:183) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:146) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:176) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.lambda$getFields$5(ObjectTypeMapper.java:90) ~[spqr-0.10.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_144]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_144]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_144]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_144]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getFields(ObjectTypeMapper.java:91) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:39) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLType(CachingMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:183) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.InterfaceMapper.lambda$getImplementingType$4(InterfaceMapper.java:82) ~[spqr-0.10.0.jar:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_144]
	at io.leangen.graphql.generator.mapping.common.InterfaceMapper.getImplementingType(InterfaceMapper.java:82) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.InterfaceMapper.lambda$registerImplementations$2(InterfaceMapper.java:65) ~[spqr-0.10.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_144]
	at io.leangen.graphql.generator.mapping.common.InterfaceMapper.registerImplementations(InterfaceMapper.java:65) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.InterfaceMapper.toGraphQLType(InterfaceMapper.java:49) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.InterfaceMapper.toGraphQLType(InterfaceMapper.java:24) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLType(CachingMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:66) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:35) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:183) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ListMapper.toGraphQLType(ListMapper.java:23) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:66) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:35) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:183) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:146) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:176) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.lambda$getFields$5(ObjectTypeMapper.java:90) ~[spqr-0.10.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_144]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_144]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_144]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_144]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getFields(ObjectTypeMapper.java:91) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:39) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLType(CachingMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:66) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:35) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:183) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:146) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:176) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.lambda$getFields$5(ObjectTypeMapper.java:90) ~[spqr-0.10.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_144]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_144]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_144]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_144]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getFields(ObjectTypeMapper.java:91) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:39) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLType(CachingMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.AbstractTypeSubstitutingMapper.toGraphQLType(AbstractTypeSubstitutingMapper.java:29) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:183) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:146) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:176) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.lambda$getFields$5(ObjectTypeMapper.java:90) ~[spqr-0.10.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_144]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_144]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_144]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_144]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getFields(ObjectTypeMapper.java:91) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:39) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLType(CachingMapper.java:31) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:197) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:183) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:146) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:176) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.lambda$generateQueries$0(OperationMapper.java:101) ~[spqr-0.10.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_144]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_144]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_144]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_144]
	at io.leangen.graphql.generator.OperationMapper.generateQueries(OperationMapper.java:102) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.generator.OperationMapper.<init>(OperationMapper.java:83) ~[spqr-0.10.0.jar:?]
	at io.leangen.graphql.GraphQLSchemaGenerator.generate(GraphQLSchemaGenerator.java:1042) ~[spqr-0.10.0.jar:?]
	...
```

**Comment by kaqqao** [comment]
This is a deep one.
The reason there are no null checks is that it should be impossible for a class to both implement an interface and not be resolvable against it at the same time. Yet, by the magic of code enhancement, it seems possible after all 😅
It's kind of good that you got the exception instead of it being silently ignored as you're now aware of this edge-case in your system. And a custom interface strategy is a perfectly reasonable thing to do in this case.

I think the default impl should either still throw an exception (just a better one than NPE, something that actually explains what went wrong) or maybe ignore nulls and log a warning... And maybe also be easy to toggle between the two... I have to think a bit.

Thanks for such a nice job on investigating this one! 😃 Would be infernal to debug otherwise.

**Comment by kaqqao** [comment]
You can now easily skip certain interfaces:

```java
new AnnotatedInterfaceStrategy(true)
                .withFilters(inter -> inter != EntityBean.class)
```

or ignore all non-resolvable:

```java
new AnnotatedInterfaceStrategy(true)
                .withUnresolvableInterfacesIgnored()
```

**Comment by frensjan** [comment]
Hi @kaqqao, that's excellent. It still eludes as to what the root cause for this glitch is, but these methods are very helpful. Thanks for this!
