### ISSUE TITLE
maximumQueryComplexity doesn't work with INTROSPECTION_QUERY

### ISSUE THREAD

**Issue by galiatsatosc** [leangen/graphql-spqr#31]
I've tried to add maximumQueryComplexity but i've seen that it breaks with INTROSPECTION_QUERY execution and some times in mutations. Simple Queries worked fine.

code:
GraphQLRuntime.newGraphQL(schema).maximumQueryComplexity(50).queryExecutionStrategy(new BatchedExecutionStrategy()).build();
graphQL.execute(IntrospectionQuery.INTROSPECTION_QUERY);

Error stack:
java.lang.NullPointerException
	at io.leangen.graphql.execution.complexity.ComplexityAnalyzer.collectFields(ComplexityAnalyzer.java:58)
	at io.leangen.graphql.execution.complexity.ComplexityAnalysisInstrumentation.beginDataFetch(ComplexityAnalysisInstrumentation.java:50)
	at graphql.execution.Execution.executeOperation(Execution.java:72)
	at graphql.execution.Execution.execute(Execution.java:49)
	at graphql.GraphQL.execute(GraphQL.java:222)
	at io.leangen.graphql.GraphQLRuntime.execute(GraphQLRuntime.java:40)
	at graphql.GraphQL.execute(GraphQL.java:187)
	at graphql.GraphQL.execute(GraphQL.java:179)
...

**Comment by emmostrom** [comment]
fieldDefinition for __schema is null which is causing a null pointer exception on the next line when trying to get fieldDefinition.getArguments()

what is the best fix for this since a lot of clients are using this to validate queries before they are sent to the server.

**Comment by kaqqao** [comment]
I only now realize I've never responded to this one 😶
Indeed, the current implementation is flaky (and kind of experimental) and only works for basic queries. It fails for introspection, mutations and probably subscriptions.

graphql-java introduced a new API for traversing the operation AST, so it may be helpful in refactoring this. I simply had no time to tackle ot earlier.

Either way, I aim to fix this feature prior to 1.0 release, which I will start working on as soon as 0.9.6 is out the door (this week in all likelihood).

**Comment by kaqqao** [comment]
This should now work reliably.
