### ISSUE TITLE
graphql.AssertException: Object required to be not null in version 0.10.1

### ISSUE THREAD

**Issue by InnuceEAN** [leangen/graphql-spqr#341]
Hi after updating from version 0.9.9 to 0.10.1 (or 0.10.0) I get the following exception when running a GraphQl query:

> graphql.AssertException: Object required to be not null
	at graphql.Assert.assertNotNull(Assert.java:29) ~[graphql-java-13.0.jar:na]
	at graphql.execution.instrumentation.DocumentAndVariables.<init>(DocumentAndVariables.java:19) ~[graphql-java-13.0.jar:na]
	at graphql.execution.instrumentation.DocumentAndVariables.<init>(DocumentAndVariables.java:13) ~[graphql-java-13.0.jar:na]
	at graphql.execution.instrumentation.DocumentAndVariables$Builder.build(DocumentAndVariables.java:55) ~[graphql-java-13.0.jar:na]
	at graphql.GraphQL.parse(GraphQL.java:578) ~[graphql-java-13.0.jar:na]
	at graphql.GraphQL.parseAndValidate(GraphQL.java:547) ~[graphql-java-13.0.jar:na]
	at graphql.GraphQL.lambda$parseValidateAndExecute$2(GraphQL.java:531) ~[graphql-java-13.0.jar:na]
	at graphql.execution.preparsed.NoOpPreparsedDocumentProvider.getDocument(NoOpPreparsedDocumentProvider.java:13) ~[graphql-java-13.0.jar:na]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:533) ~[graphql-java-13.0.jar:na]
	at graphql.GraphQL.executeAsync(GraphQL.java:502) ~[graphql-java-13.0.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:432) ~[graphql-java-13.0.jar:na]
	at io.leangen.graphql.spqr.spring.web.servlet.DefaultGraphQLExecutor.execute(DefaultGraphQLExecutor.java:23) ~[graphql-spqr-spring-boot-autoconfigure-0.0.4.jar:na]
	at io.leangen.graphql.spqr.spring.web.servlet.DefaultGraphQLExecutor.execute(DefaultGraphQLExecutor.java:11) ~[graphql-spqr-spring-boot-autoconfigure-0.0.4.jar:na]
	at io.leangen.graphql.spqr.spring.web.GraphQLController.executeJsonPost(GraphQLController.java:42) ~[graphql-spqr-spring-boot-autoconfigure-0.0.4.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	(...)

The offending query is:
```
@Service
@GraphQLApi
public class MeasurementService {
	@GraphQLQuery
	public String test() {
		return "hi";
	}
}
```

**Comment by kaqqao** [comment]
SPQR versions are not always backwards compatible, so you can't simply change the version used by Spring Starter and expect it to work. I'm currently on vacation but I'll release a new Starter version compatible with the latest SPQR. If you want, you can try the current master for yourself.

**Comment by kaqqao** [comment]
Additionally, please open Starter related issues in that project, not SPQR core (this project).
