### ISSUE TITLE
Get Selection Set Fields from within a Mutation No Longer Working (0.11.0)

### ISSUE THREAD

**Issue by austinarbor** [leangen/graphql-spqr#375]
Hi @kaqqao  thanks for working on this project and getting a new version out. When testing the latest release with my project, I found that trying to fetch all of the selection set fields from the `ResolutionEnvironment` from a mutation no longer works.

```java
@GraphQLMutation(name = "saveData")
public Model saveData(@GraphQLNonNull Integer id, @GraphQLEnvironment ResolutionEnvironment env) {
     List<SelectedField> fields = env.dataFetchingEnvironment.getSelectionSet().getFields(); // this now throws an error
     log.info("Fields: {}", fields);
     return new Model();
}
```

I have created a sample project [here](https://github.com/austinarbor/graphql-spqr-get-fields-issue) to demonstrate.

If you run the mutation 
```graphql
mutation {
  saveData(id: 1) {
   id
   name
 }
}
```

You can see the exception 
```java
graphql.AssertException: no field with name saveData found in object Query
	at graphql.Assert.assertNotNull(Assert.java:17) ~[graphql-java-16.1.jar:na]
	at graphql.normalized.FieldCollectorNormalizedQuery.collectField(FieldCollectorNormalizedQuery.java:218) ~[graphql-java-16.1.jar:na]
	at graphql.normalized.FieldCollectorNormalizedQuery.collectFields(FieldCollectorNormalizedQuery.java:132) ~[graphql-java-16.1.jar:na]
	at graphql.normalized.FieldCollectorNormalizedQuery.collectFromOperation(FieldCollectorNormalizedQuery.java:107) ~[graphql-java-16.1.jar:na]
	at graphql.normalized.NormalizedQueryTreeFactory.createNormalizedQueryImpl(NormalizedQueryTreeFactory.java:55) ~[graphql-java-16.1.jar:na]
	at graphql.normalized.NormalizedQueryTreeFactory.createNormalizedQuery(NormalizedQueryTreeFactory.java:35) ~[graphql-java-16.1.jar:na]
	at graphql.execution.ExecutionContext.lambda$getNormalizedQueryTree$0(ExecutionContext.java:207) ~[graphql-java-16.1.jar:na]
	at graphql.util.InterThreadMemoizedSupplier.get(InterThreadMemoizedSupplier.java:31) ~[graphql-java-16.1.jar:na]
	at graphql.execution.ExecutionStrategy.lambda$getNormalizedField$6(ExecutionStrategy.java:296) ~[graphql-java-16.1.jar:na]
	at graphql.schema.DataFetchingFieldSelectionSetImpl.computeValuesLazily(DataFetchingFieldSelectionSetImpl.java:196) ~[graphql-java-16.1.jar:na]
```

In my project we use the selection set fields to dynamically generate an `EntityGraph` which we subsequently pass into JPA to automatically fetch the required data using left-joins rather than create n+1 queries to fetch all of the associations.

Thanks

**Comment by kaqqao** [comment]
`DataFetchingEnvironment` and everything under it is all coming directly from graphql-java itself (you can see no mention of spqr in the stack trace), so it could be a bug there... But this API is quite fundamental, so it would be rather surprising for it to be broken without graphql-java folks being alarmed already... Hm... I'll poke around a bit.

**Comment by kaqqao** [comment]
Ok, after having a brief look into `DataFetchingEnvironment#getSelectionSet()` I would no longer be surprised if dragons live there. That code got so complex since the last time I've looked into it that I have _no clue_ what's going on. Traversers, synchronization, memoized suppliers and eldritch horrors 😱
Anyway, seems to me there very much is a bug as this line assumes the root type is always the query type. With for a mutation clearly isn't true... Will raise an issue there.

**Comment by kaqqao** [comment]
There already is [an issue](https://github.com/graphql-java/graphql-java/issues/2117) open. So we play the waiting game...

**Comment by austinarbor** [comment]
Thanks for looking into it, I didn't think to check the main graphql project. Unfortunately looks like that issue / PR fix has stalled :weary: 

Sine the root cause is upstream feel free to close this out if you want

**Comment by austinarbor** [comment]
I created pretty much duplicate PR with their suggested assertion fix https://github.com/graphql-java/graphql-java/pull/2173

**Comment by kaqqao** [comment]
There's a conflict in a test file for some reason (did it really get changed in the meantime 🤔). Probably better to deal with or else this PR also gets stuck 😩

**Comment by austinarbor** [comment]
Nice catch, fixed it

**Comment by austinarbor** [comment]
graphql-java 16.2 released with this fix https://github.com/graphql-java/graphql-java/releases/tag/v16.2
