### ISSUE TITLE
Kotlin isX field is excluded on input types

### ISSUE THREAD

**Issue by IceBlizz6** [leangen/graphql-spqr#465]
In Kotlin i have this class
```
class PostUpdate(
	val isDelivered: Boolean
)
```

Using javap then i see that this is equivalent to:
```
public class PostUpdate {
  private final boolean isDelivered;
  public PostUpdate(boolean);
  public final boolean isDelivered();
}
```

Trying to set up this as a unit test:
```
public class PostUpdate {
	private final boolean isDelivered;
	
	public PostUpdate(boolean isDelivered) {
		this.isDelivered = isDelivered;
	}

	public boolean isDelivered() {
		return isDelivered;
	}
}

public class PostService {
	@GraphQLQuery
	public void update(int id, PostUpdate input) {
		throw new RuntimeException("Not implemented");
	}
}

@Test
public void updatePostTest() {
	new GraphQLSchemaGenerator()
			.withOperationsFromSingleton(new PostService())
			.generateExecutable();
}
```

this unit test then fails:
> 
> graphql.schema.validation.InvalidSchemaException: invalid schema:
> "PostUpdateInput" must define one or more fields.
> 
> 	at graphql.schema.GraphQLSchema$Builder.validateSchema(GraphQLSchema.java:945)
> 	at graphql.schema.GraphQLSchema$Builder.buildImpl(GraphQLSchema.java:939)
> 	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:904)
> 	at io.leangen.graphql.GraphQLSchemaGenerator.generateExecutable(GraphQLSchemaGenerator.java:993)
> 	at io.leangen.graphql.BatchingTest.updatePostTest(BatchingTest.java:50)

Renaming isDelivered field to delivered will pass the unit test.
However this is not a working solution because my code was generated from kotlin.

I can understand that it is unfortunate that Kotlin does not follow boolean naming convention in this regard.
Sadly i have a lot of classes like this in my Kotlin project, most of these are auto generated.
Would it be possible to solve this?

**Comment by kaqqao** [comment]
There is a recent similar issue already open. SPQR (well, `BeanResolverBuilder` to be precise) will only expose properties that adhere to the JavaBeans spec. This means the accessor for a field called `isX` must be called `isIsX` or `getIsX`. SPQR has no way to reliably detect a method that acts as an accessor but violates the spec.
What I'd normally suggest is to add `@GraphQLQuery` to the accessor (`isDelivered()`) in your case, but I have idea if this is something you can do in Kotlin, since these methods are autogenerated, and since I know next to nothing about Kotlin. But it'd be rather surprising if you can't. If such a one-off solution doesn't sit well (e.g because you have this situation in multiple places and don't want to have to think of it), you can implement a custom `ResolverBuilder` and register it via `generator.withNestedResolverBuilder`. If you end up going that route, you could also be cool and contribute that impl to the project 😇 You may as well write it in Kotlin, and it could be the start of the SPQR Kotlin module that I've been meaning to get to obe day.

**Comment by kaqqao** [comment]
Oh. If `PostUpdate` models simple data objects, you may as well use `PublicResolverBuilder` for it (or for all such classes). It will expose _all_ public methods, which may be exactly what you're after anyway?

**Comment by IceBlizz6** [comment]
Looks like adding jackson-module-kotlin solved this issue.
I like your idea of having a kotlin module for spqr.
I may be able to contribute something.
Right now i have:
* Type mapper that applies Kotlin nullability
* Resolver builder that removes/ignores Companion objects
* Type mapper that allows kotlin Flow to be used for subscriptions.
* Schema transformer that preserves original kotlin property name, rather than losing 'is' and 'get' prefixes.

Maybe we should continue this in a new discussion as i think this specific issue has been solved.

**Comment by kaqqao** [comment]
Ooh, sorry, I was completely off. All I said was about _output_ types, and you were talking about _input_ types. Yes, SPQR delegates the discovery of input fields to Jackson (or Gson). This way it avoids the insidious problem of everything seeming ok but failing to deserialize at runtime. Most Jackson configs should thus transparently work. So if you add the Jackson Kotlin module, making Jackson aware of Kotlin's quirky accessor naming, it should just start working in SPQR too, yeah.

And yes, let's continue the Kotlin SPQR module discussion elsewhere.
