### ISSUE TITLE
Exception while calling findClassLoaderOrder for nonapi.io.github.classgraph.classloaderhandler.QuarkusClassLoaderHandler

### ISSUE THREAD

**Issue by nirue** [leangen/graphql-spqr#517]
After updating Quarkus to 3.16.1, SPQR 0.12.4 gives the following error message, when generating an ExecutableSchema.

Any ideas, how to solve this issue?

`ExecutableSchema schema = new GraphQLSchemaGenerator()
                .withBasePackages(AppConstants.BASE_PACKAGES)
                .generateExecutable();`

> java.lang.RuntimeException: Exception while calling findClassLoaderOrder for nonapi.io.github.classgraph.classloaderhandler.QuarkusClassLoaderHandler                                                        
        at nonapi.io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry$ClassLoaderHandlerRegistryEntry.findClasspathOrder(ClassLoaderHandlerRegistry.java:239)                                 
        at nonapi.io.github.classgraph.classpath.ClasspathFinder.<init>(ClasspathFinder.java:276)                                                                                                            
        at io.github.classgraph.Scanner.<init>(Scanner.java:168)                                                                                                                                             
        at io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1562)                                                                                                                                   
        at io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1590)                                                                                                                                   
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1615)                                                                                                                                        
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1654)                                                                                                                                        
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1667)                                                                                                                                        
        at io.leangen.graphql.util.ClassFinder.lambda$findImplementations$5(ClassFinder.java:73)                                                                                                             
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1713)                                                                                                     
        at io.leangen.graphql.util.ClassFinder.findImplementations(ClassFinder.java:69)                                                                                                                      
        at io.leangen.graphql.util.ClassFinder.findImplementations(ClassFinder.java:53)                                                                                                                      
        at io.leangen.graphql.generator.mapping.strategy.DefaultImplementationDiscoveryStrategy.findImplementations(DefaultImplementationDiscoveryStrategy.java:46)                                          
        at io.leangen.graphql.generator.mapping.common.InterfaceMapper.registerImplementations(InterfaceMapper.java:68)                                                                                      
        at io.leangen.graphql.generator.mapping.common.InterfaceMapper.toGraphQLType(InterfaceMapper.java:51)                                                                                                
        at io.leangen.graphql.generator.mapping.common.InterfaceMapper.toGraphQLType(InterfaceMapper.java:24)                                                                                                
        at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLType(CachingMapper.java:31)                                                                                                    
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:202)                                                                                                              
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:187)                                                                                                              
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.lambda$getInterfaces$6(ObjectTypeMapper.java:111)                                                                                    
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1074)                                                                                                                                     
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getInterfaces(ObjectTypeMapper.java:110)                                                                                             
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:45)                                                                                              
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:32)                                                                                              
        at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLType(CachingMapper.java:31)                                                                                                    
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:202)                                                                                                              
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:187)                                                                                                              
        at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:147)                                                                                                             
        at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:178)                                                                                                             
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.lambda$getFields$5(ObjectTypeMapper.java:98)                                                                                         
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)                                                                                                               
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1788)                                                                                                                  
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)                                                                                                                   
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)                                                                                                            
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)                                                                                                              
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)                                                                                                                   
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727)                                                                                                                  
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getFields(ObjectTypeMapper.java:99)                                                                                                  
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:42)                                                                                              
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:32)                                                                                              
        at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLType(CachingMapper.java:31)                                                                                                    
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:202)                                                                                                              
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:187)                                                                                                              
        at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:147)                                                                                                             
        at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:178)                                                                                                             
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.lambda$getFields$5(ObjectTypeMapper.java:98)                                                                                         
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)                                                                                                               
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1788)                                                                                                                  
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)                                                                                                                   
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)                                                                                                            
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)                                                                                                              
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)                                                                                                                   
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727)                                                                                                                  
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getFields(ObjectTypeMapper.java:99)                                                                                                  
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:42)                                                                                              
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:32)                                                                                              
        at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLType(CachingMapper.java:31)                                                                                                    
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:202)                                                                                                              
        at io.leangen.graphql.generator.mapping.common.AbstractTypeSubstitutingMapper.toGraphQLType(AbstractTypeSubstitutingMapper.java:28)                                                                  
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:202)                                                                                                              
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:187)                                                                                                              
        at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:147)                                                                                                             
        at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:178)                                                                                                             
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.lambda$getFields$5(ObjectTypeMapper.java:98)                                                                                         
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)                                                                                                               
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1788)                                                                                                                  
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)                                                                                                                   
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)                                                                                                            
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)                                                                                                              
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)                                                                                                                   
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727)                                                                                                                  
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getFields(ObjectTypeMapper.java:99)                                                                                                  
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:42)                                                                                              
        at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:32)                                                                                              
        at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLType(CachingMapper.java:31)                                                                                                    
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:202)                                                                                                              
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:187)                                                                                                              
        at io.leangen.graphql.generator.mapping.common.ListMapper.toGraphQLType(ListMapper.java:23)                                                                                                          
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:202)                                                                                                              
        at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:75)                                                                                                    
        at io.leangen.graphql.generator.mapping.common.NonNullMapper.toGraphQLType(NonNullMapper.java:27)                                                                                                    
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:202)                                                                                                              
        at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:187)                                                                                                              
        at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:147)                                                                                                             
        at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:178)                                                                                                             
        at io.leangen.graphql.generator.OperationMapper.lambda$generateQueries$0(OperationMapper.java:84)                                                                                                    
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)                                                                                                               
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)                                                                                                          
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)                                                                                                                   
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)                                                                                                            
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)                                                                                                              
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)                                                                                                                   
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727)                                                                                                                  
        at io.leangen.graphql.generator.OperationMapper.generateQueries(OperationMapper.java:85)                                                                                                             
        at io.leangen.graphql.generator.OperationMapper.<init>(OperationMapper.java:65)                                                                                                                      
        at io.leangen.graphql.GraphQLSchemaGenerator.generateExecutable(GraphQLSchemaGenerator.java:953)                                                                                                     
        at net.xyz.graph.graphql.producer.GraphQLSchemaProducer.getExecutableSchema(GraphQLSchemaProducer.java:83)                                                                                     
        at net.xyz.graph.graphql.producer.GraphQLSchemaProducer_ProducerMethod_getExecutableSchema_6fbK5MO7Jt_lnyUvIvMtOd8DDcY_Bean.doCreate(Unknown Source)                                           
        at net.xyz.graph.graphql.producer.GraphQLSchemaProducer_ProducerMethod_getExecutableSchema_6fbK5MO7Jt_lnyUvIvMtOd8DDcY_Bean.create(Unknown Source)                                             
        at net.xyz.graph.graphql.producer.GraphQLSchemaProducer_ProducerMethod_getExecutableSchema_6fbK5MO7Jt_lnyUvIvMtOd8DDcY_Bean.get(Unknown Source)                                                
        at net.xyz.graph.graphql.producer.GraphQLSchemaProducer_ProducerMethod_getExecutableSchema_6fbK5MO7Jt_lnyUvIvMtOd8DDcY_Bean.get(Unknown Source)                                                
        at net.xyz.graph.rest.resource.GqlHttpEndpoint_Bean.doCreate(Unknown Source)                                                                                                                   
        at net.xyz.graph.rest.resource.GqlHttpEndpoint_Bean.create(Unknown Source)                                                                                                                     
        at net.xyz.graph.rest.resource.GqlHttpEndpoint_Bean.create(Unknown Source)                                                                                                                     
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)                                                                                                    
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)                                                                                                                    
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)                                                                                                                    
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)                                                                                                                                              
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)                                                                                                                        
        at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)                                                                                        
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)                                                                                                                      
        at net.xyz.graph.rest.resource.GqlHttpEndpoint_Bean.get(Unknown Source)                                                                                                                        
        at net.xyz.graph.rest.resource.GqlHttpEndpoint_Bean.get(Unknown Source)                                                                                                                        
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:559)                                                                                                                
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:539)                                                                                                                
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:572)                                                                                                                
        at io.quarkus.arc.impl.ArcContainerImpl$3.get(ArcContainerImpl.java:331)                                                                                                                             
        at io.quarkus.arc.impl.ArcContainerImpl$3.get(ArcContainerImpl.java:328)                                                                                                                             
        at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:52)                                                                                       
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:64)                                                                                 
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:349)                                                                                                              
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)                                                                                                               
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)                                                                                                              
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)                                                                                                     
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)                                                                                                 
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)                                                                       
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)                                                                                                          
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)                                                                                                              
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:84)                                                                                                       
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)                                                                                                 
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:97)                                                                                                     
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:627)                                                                                                            
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)                                                                                                           
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)                                                                                                                 
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)                                                                                                            
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)                                                                                                           
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)                                                                                                                              
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)                                                                                                          
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                                                             
        at java.base/java.lang.Thread.run(Thread.java:1575)                                                                                                                                                  
Caused by: java.lang.reflect.InvocationTargetException                                                                                                                                                       
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:115)                                                                                             
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)                                                                                                                                        
        at nonapi.io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry$ClassLoaderHandlerRegistryEntry.findClasspathOrder(ClassLoaderHandlerRegistry.java:236)                                 
        ... 139 more                                                                                                                                                                                         
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because the return value of "nonapi.io.github.classgraph.reflection.ReflectionUtils.getFieldVal(boolean, Object, String)" is null                                                                                                                                                                                              
        at nonapi.io.github.classgraph.classloaderhandler.QuarkusClassLoaderHandler.findClasspathOrderForQuarkusClassloader(QuarkusClassLoaderHandler.java:120)                                              
        at nonapi.io.github.classgraph.classloaderhandler.QuarkusClassLoaderHandler.findClasspathOrder(QuarkusClassLoaderHandler.java:111)                                                                   
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)                                                                                             
        ... 141 more                                                                                                                                                                                         
2024-11-01 13:13:04,878 ERROR [net.xyz.gra.res.map.CustomExceptionMapper] (executor-thread-1) Cannot invoke "io.leangen.graphql.ExecutableSchema.getSchema()" because "this.executableSchema" is null        
2024-11-01 13:13:05,005 ERROR [net.xyz.gra.res.map.CustomExceptionMapper] (executor-thread-1) Cannot invoke "io.leangen.graphql.ExecutableSchema.getSchema()" because "this.executableSchema" is null

**Comment by kaqqao** [comment]
I can experiment a bit, but first try using the latest version of ClassGraph, maybe the issue's already fixed there, as it seems the exception isn't coming from SPQR itself.
At worst, the class finder can be replaced with something else, including something Quarkus specific (maybe Jandex, or even a runtime check for the registered beans of the correct type).

**Comment by nirue** [comment]
>         
           <dependency>
            <groupId>io.leangen.graphql</groupId>
            <artifactId>spqr</artifactId>
            <version>${spqr.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>io.github.classgraph</groupId>
                    <artifactId>classgraph</artifactId>
                </exclusion>
            </exclusions>
        </dependency> 
        <dependency>
            <groupId>io.github.classgraph</groupId>
            <artifactId>classgraph</artifactId>
            <version>4.8.177</version>
        </dependency> 

Unfortunately replacing the ClassGraph Dep with the newest one does not fix the issue.

**Comment by nirue** [comment]
@kaqqao 
Good news, Classgraph version 4.8.179 fixed the issue.
Please update the Classgraph dependency for the next SPQR version.
