### ISSUE TITLE
Duplicate annotation error when attempting to specify non-null list of non-null elements

### ISSUE THREAD

**Issue by jmhain** [leangen/graphql-spqr#75]
I want the following to produce a field on `Case` with type `[Note!]!`, so I attempted that with the following.

```
    @GraphQLQuery(name = "notes")
    public @GraphQLNonNull List<@GraphQLNonNull Note> getNotes(@GraphQLContext Case c) {
        ...
    }

```

But the schema generation fails with this stacktrace:

```
Caused by: java.lang.annotation.AnnotationFormatError: Duplicate annotation for class: interface io.leangen.graphql.annotations.GraphQLNonNull: @io.leangen.graphql.annotations.GraphQLNonNull()
	at sun.reflect.annotation.TypeAnnotationParser.mapTypeAnnotations(TypeAnnotationParser.java:360)
	at sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl.<init>(AnnotatedTypeFactory.java:139)
	at sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedParameterizedTypeImpl.<init>(AnnotatedTypeFactory.java:240)
	at sun.reflect.annotation.AnnotatedTypeFactory.buildAnnotatedType(AnnotatedTypeFactory.java:77)
	at sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedType(TypeAnnotationParser.java:79)
	at java.lang.reflect.Executable.getAnnotatedReturnType0(Executable.java:633)
	at java.lang.reflect.Method.getAnnotatedReturnType(Method.java:648)
	at io.leangen.geantyref.GenericTypeReflector.getReturnType(GenericTypeReflector.java:532)
	at io.leangen.geantyref.GenericTypeReflector.getReturnType(GenericTypeReflector.java:518)
	at io.leangen.graphql.util.ClassUtils.getReturnType(ClassUtils.java:139)
	at io.leangen.graphql.metadata.execution.MethodInvoker.resolveReturnType(MethodInvoker.java:36)
	at io.leangen.graphql.metadata.execution.MethodInvoker.<init>(MethodInvoker.java:21)
	at io.leangen.graphql.metadata.execution.SingletonMethodInvoker.<init>(SingletonMethodInvoker.java:15)
	at io.leangen.graphql.metadata.strategy.query.AnnotatedResolverBuilder.lambda$buildQueryResolvers$0(AnnotatedResolverBuilder.java:58)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.leangen.graphql.metadata.strategy.query.AnnotatedResolverBuilder.buildQueryResolvers(AnnotatedResolverBuilder.java:75)
	at io.leangen.graphql.metadata.strategy.query.AnnotatedResolverBuilder.buildQueryResolvers(AnnotatedResolverBuilder.java:44)
	at io.leangen.graphql.generator.OperationRepository.lambda$buildQueryResolvers$16(OperationRepository.java:137)
	at 
io.leangen.graphql.generator.OperationRepository.lambda$null$19(OperationRepository.java:154)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.leangen.graphql.generator.OperationRepository.buildResolvers(OperationRepository.java:156)
	at io.leangen.graphql.generator.OperationRepository.buildQueryResolvers(OperationRepository.java:136)
	at io.leangen.graphql.generator.OperationRepository.<init>(OperationRepository.java:33)
	at io.leangen.graphql.GraphQLSchemaGenerator.generate(GraphQLSchemaGenerator.java:788)
```
I found a test class in this repo doing the same thing (`io.leangen.graphql.services.RecService`), so clearly this is supported. What am I doing wrong?

**Comment by kaqqao** [comment]
Yes, this is definitely supported. I've tried just now replicating your issue, but couldn't... There has to be something more special about your case.
Here's a screenshot of both the minimal example I used and the debugger view of the resulting schema:

![non-null list of non-nulls](https://user-images.githubusercontent.com/831171/36846329-8ce6b93a-1d5a-11e8-840e-f65e0476112d.png)

Maybe you have `@GraphQLNonNull` in more places so it somehow got duplicated? SPQR will copy the parameter annotations onto the field type for example, so it could erroneously duplicate it that way?

**Comment by jmhain** [comment]
Thanks for looking at this - I spent quite a few hours trying to figure it out last night.

I discovered that the failure occurs only when IntelliJ compiles the class; it works as expected when running a gradle-built version.

I decompiled the class files built by each.

__IntelliJ__:
``` 
    @GraphQLQuery(
        name = "notes"
    )
    @GraphQLNonNull
    @GraphQLNonNull
    public List<Note> getNotes(@GraphQLContext Case c) {
```

__Gradle__
```
    @GraphQLQuery(
        name = "notes"
    )
    @GraphQLNonNull
    public List<Note> getNotes(@GraphQLContext Case c) {
```

Both built by the same JDK (1.8.0_161). Decompiled classes are otherwise identical. At this point I'm pretty sure this is not an issue with graphql-spqr, but if you have any ideas I would greatly appreciate hearing them.

**Comment by kaqqao** [comment]
Wow. This... is unexpected. I'm also using IntelliJ and the exact same JDK version (1.8.0_161), but haven't ever experienced this.
Maybe try messing around with _Java Compiler_ options in IntelliJ, updating if there's anything to update, try a clean install etc... And I guess open an issue with JetBrains?

**Comment by jmhain** [comment]
Okay, I think I found the issue, and it does look like a bug in IntelliJ, specifically with its null analysis inspection. 

As a test, I created a local copy of `@GraphQLNonNull` called `@MyNonNull`, and a test class with this method:
```    
    public @MyNonNull List<@MyNonNull String> getValue() {
        return Collections.emptyList();
    }
```
The compiled class did not have a duplicate annotation.

Then I added a second method.
```
    public @GraphQLNonNull List<@GraphQLNonNull String> getValue2() {
        return Collections.emptyList();
    }
```

The compiled result of this was very interesting:

```    
    @MyNonNull
    @MyNonNull
    public List<String> getValue() {
        return Collections.emptyList();
    }

    @GraphQLNonNull
    @GraphQLNonNull
    public List<String> getValue2() {
        return Collections.emptyList();
    }
        
```

So then I remembered that I had added `@GraphQLNonNull` to IntelliJ's list of annotations for null inspection, and it turns out that if I replace `@GraphQLNonNull` with `@NotNull` (org.jetbrains.annotations) in the above example, the exact same thing occurs. The issue goes away if I disable the IntelliJ inspection called `@NotNull/@Nullable` problems.

Interestingly, it's not enough to just remove `@GraphQLNonNull` from the annotations list, because a single annotation from _any_ on the list will cause all of them in the class to be duplicated when used in this way. This explains why I had so much trouble debugging this issue - this code base uses jetbrains `@NotNull`/`@Nullable` pervasively.

**Comment by kaqqao** [comment]
Ah, no wonder I couldn't reproduce...

In the current master (soon to be the 0.9.7 release), JetBrains' `@NotNull` and a few other annotations are mapped to GraphQL non-null types automatically. (But it's rather easy to add stuff like that yourself too)

In 0.9.6 and earlier, only `@GraphQLNonNull` and `javax.annotations.Nonnull` are respected.
