### ISSUE TITLE
SchemaGenerator not working on dynamically generated objects

### ISSUE THREAD

**Issue by evader1337** [leangen/graphql-spqr#76]
I was playing around with this extension and noticed, that when you pass dynamically generated object to function .withOperationsFromSingleton it doesn't work. For example:
`return generator.withOperationsFromSingleton(Class.forName("Test").getConstructor().newInstance()).generate();` fails on generate call producing NullPointerException. It works normally, if I input `new Test()` as parameter. 

Full stack trace:
```
java.lang.NullPointerException
	at io.leangen.graphql.metadata.strategy.query.PublicResolverBuilder.isPackageAcceptable(PublicResolverBuilder.java:129)
	at io.leangen.graphql.metadata.strategy.query.PublicResolverBuilder.lambda$buildQueryResolvers$0(PublicResolverBuilder.java:63)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.leangen.graphql.metadata.strategy.query.PublicResolverBuilder.buildQueryResolvers(PublicResolverBuilder.java:75)
	at io.leangen.graphql.metadata.strategy.query.PublicResolverBuilder.buildQueryResolvers(PublicResolverBuilder.java:46)
	at io.leangen.graphql.generator.OperationRepository.lambda$buildQueryResolvers$16(OperationRepository.java:137)
	at io.leangen.graphql.generator.OperationRepository.lambda$null$19(OperationRepository.java:154)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.leangen.graphql.generator.OperationRepository.buildResolvers(OperationRepository.java:156)
	at io.leangen.graphql.generator.OperationRepository.buildQueryResolvers(OperationRepository.java:136)
	at io.leangen.graphql.generator.OperationRepository.buildNestedQueries(OperationRepository.java:132)
	at io.leangen.graphql.generator.OperationRepository.getNestedQueries(OperationRepository.java:108)
	at io.leangen.graphql.generator.OperationRepository.getChildQueries(OperationRepository.java:114)
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.getFields(ObjectTypeMapper.java:82)
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:39)
	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLType(ObjectTypeMapper.java:31)
	at io.leangen.graphql.generator.mapping.common.CachingMapper.graphQLType(CachingMapper.java:28)
	at io.leangen.graphql.generator.mapping.common.AbstractionCollectingMapper.toGraphQLType(AbstractionCollectingMapper.java:28)
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:171)
	at io.leangen.graphql.generator.mapping.common.ListMapper.toGraphQLType(ListMapper.java:23)
	at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:171)
	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:136)
	at io.leangen.graphql.generator.OperationMapper.lambda$generateQueries$0(OperationMapper.java:90)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.leangen.graphql.generator.OperationMapper.generateQueries(OperationMapper.java:91)
	at io.leangen.graphql.generator.OperationMapper.<init>(OperationMapper.java:74)
	at io.leangen.graphql.GraphQLSchemaGenerator.generate(GraphQLSchemaGenerator.java:794)
	at com.kumuluz.ee.graphql.servlets.GraphQLServlet.buildSchema(GraphQLServlet.java:91)
	at com.kumuluz.ee.graphql.servlets.GraphQLServlet.processQuery(GraphQLServlet.java:60)
	at com.kumuluz.ee.graphql.servlets.GraphQLServlet.doPost(GraphQLServlet.java:37)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at com.kumuluz.ee.common.filters.PoweredByFilter.doFilter(PoweredByFilter.java:43)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kaqqao** [comment]
Can't seem to replicate... Are you on the latest version? Is there anything special about the `Test` class? The only reason you'd get this exception is if the package `Test` belongs to was somehow `null`.

Could you place a break point at the line mentioned in the stacktrace and see what is going on?

**Comment by evader1337** [comment]
I have found the problem. This only happens when the class you are trying to initialize is without package.

**Comment by kaqqao** [comment]
The only way for a package to be null is if the classloader has not yet loaded any classes from that package. Which means when you reference the `Test` class normally, a different loader loads it than when you use `Class.forName`. If you're in a app server, OSGI or another similarly complex environment, this can easily happen. In general, `Class.forName` without an explicit class loader is evil and should not be used. Try explicitly providing ` Thread.currentThread().getContextClassLoader()` as the classloader (or use SPQR's `ClassUtils.forName` which does the same thing) and you'll probably get the expected behavior.

I'll improve the error handling around this a bit in SPQR, but the issue is not with SPQR, so I can't do much - you have to take care about classloading yourself...

**Comment by kaqqao** [comment]
Also, make sure you never have the same class available in multiple locations (like packaged into the WAR, and again into the EAR). This will almost surely leave you in a classloading hell.

**Comment by evader1337** [comment]
My problem wasn't that complicated. In my sample project I had a few files which were completely without packages. In my main project I had annotation processor which wrote classes to file (because there was no package it only wrote Test to the file). When I read that file in the main project, I tried to intialize that class but it didn't work. Just by addind classes, it works now. Thank you for your assitance, the library is great and very usefull.

**Comment by kaqqao** [comment]
Oh, I see! So the default package is also null? Argh.
I'll see what I can do about it.

Thanks for the kind words!

**Comment by evader1337** [comment]
No problem. I want to explore this library further to see its full potential, but I'm a bit new to Java in general. Any tips on where to start?

**Comment by kaqqao** [comment]
Fixed the default package thingy.
As for the good starting points... The obvious place would be [the sample project](https://github.com/leangen/graphql-spqr-samples). It shows a simple way to start with Spring and GraphQL SPQR.
I'm working on a proper tutorial as well, but... it takes a lot of time that I'd rather spend bug fixing right now.

For the moment, I'd say just start with the sample and look at some of the tests, and if you get stuck ask on the [Gitter channel](https://gitter.im/leangen/graphql-spqr) and I'll help you out :)
